trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
  - pipeline: newpipeline # Name of the pipeline resource.
    source: varunthamishetti.maven-web-application (1) # The name of the pipeline referenced by this pipeline resource.
    project: Testing-pipeline # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: 'my-java-artifact'
    publishLocation: 'Container'
